baseurl: "https://leafwing-studios.com/"
title: Leafwing Studios
author: Leafwing Studios
theme: leafwing
languageCode: en-ca

outputs:
    home:
        - HTML
        - RSS
        - JSON # Necessary for search

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: Leafwing Studios
  description: Emergent complexity for thoughtful games
  github: "https://github.com/Leafwing-Studios"
  dateFormat: "2006-01-02"

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: Projects
      url: /projects/
      weight: 2
    - name: About
      url: /page/about/
      weight: 3
