baseurl: "http://leafwing-studios.com/"
title: Leafwing Studios
author: Leafwing Studios
theme: leafwing
languageCode: en-ca

outputs:
    home:
        - HTML
        - RSS
        - JSON # Necessary for search

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: Leafwing Studios
  description: The official home of the Leafwing Studios game development team
  github: "https://github.com/Leafwing-Studios"
  dateFormat: "2006-01-02"
  homeInfoParams:
    title: Leafwing Studios Blog
    content: Emergent complexity for thoughtful games

permalinks:
  post: "/post/:filename/"

menu:
  main:
    - name: Projects
      url: /projects/
      weight: 1
    - name: Blog
      url: /
      weight: 2
    - name: About
      url: /about/
      weight: 3